# Generated by Django 4.0.2 on 2022-03-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='formato',
            field=models.CharField(choices=[('Z', '-----------'), ('A', 'Lider'), ('B', 'Express'), ('C', 'SBA'), ('D', 'Mayorista'), ('E', 'Logistica'), ('F', 'Omnicanalidad')], default='Z', max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='proj_type',
            field=models.CharField(choices=[('Z', '-----------'), ('A', 'Obra Nueva'), ('B', 'Remodelacion'), ('C', 'Reconstruccion'), ('D', 'Roll-Out')], default='Z', max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.user'),
        ),
    ]
