# Generated by Django 4.0.2 on 2022-03-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_formato_alter_file_proj_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='formato',
            field=models.CharField(choices=[('-----------', '-----------'), ('Lider', 'Lider'), ('Express', 'Express'), ('SBA', 'SBA'), ('Mayorista', 'Mayorista'), ('Logistica', 'Logistica'), ('Omnicanalidad', 'Omnicanalidad')], default='Z', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='proj_type',
            field=models.CharField(choices=[('-----------', '-----------'), ('Obra Nueva', 'Obra Nueva'), ('Remodelacion', 'Remodelacion'), ('Reconstruccion', 'Reconstruccion'), ('Roll-Out', 'Roll-Out')], default='Z', max_length=100),
        ),
    ]
