# Generated by Django 4.0.2 on 2022-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_file_formato_alter_file_proj_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='add',
        ),
        migrations.AddField(
            model_name='file',
            name='complete',
            field=models.ManyToManyField(related_name='complete', to='app.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(related_name='files', to='app.File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.ManyToManyField(related_name='completed', to='app.User'),
        ),
    ]
