# Generated by Django 4.0.2 on 2022-03-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_file_add_file_complete_task_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.ManyToManyField(related_name='completed', to='app.File'),
        ),
    ]
