# Generated by Django 4.0.2 on 2022-03-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.user'),
        ),
        migrations.CreateModel(
            name='Exp_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel2', to='app.file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel1', to='app.task')),
            ],
        ),
    ]
