# Generated by Django 4.0.2 on 2022-03-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_file_user_exp_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userss', to='app.user'),
        ),
    ]
