# Generated by Django 4.0.2 on 2022-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_file_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp_task',
            old_name='completado',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
