# Generated by Django 4.0.2 on 2022-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_completado_exp_task_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp_task',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AlterField(
            model_name='file',
            name='formato',
            field=models.CharField(choices=[('-----------', '-----------'), ('Lider', 'Lider'), ('Express', 'Express'), ('SBA', 'SBA'), ('Mayorista', 'Mayorista'), ('Logistica', 'Logistica'), ('Omnicanalidad', 'Omnicanalidad')], default='-----------', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='proj_type',
            field=models.CharField(choices=[('-----------', '-----------'), ('Obra Nueva', 'Obra Nueva'), ('Remodelacion', 'Remodelacion'), ('Reconstruccion', 'Reconstruccion'), ('Roll-Out', 'Roll-Out')], default='-----------', max_length=100),
        ),
    ]
