# Generated by Django 4.0.2 on 2022-03-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_uploaded_by_id_book_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users_who_like',
            new_name='users_like',
        ),
    ]
