# Generated by Django 3.2.12 on 2022-02-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='cede',
        ),
    ]
