# Generated by Django 3.2.12 on 2022-02-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_rename_dojo_ninja_cede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='cede',
            new_name='sede',
        ),
    ]
