# Generated by Django 3.2.12 on 2022-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0003_rename_cede_ninja_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Dojo Antiguo'),
        ),
    ]
